export const filterMenuItems = [
	{
		label: "Cartoon",
		imgUrl: "/img-filter/cartoon.jpeg",
		backgroundColor: "bg-red-400",
		width: 736,
		height: 869,
	},
	{
		label: "Dart Vader",
		imgUrl: "/img-filter/darth-vader.jpg",
		backgroundColor: "bg-blue-400",
		width: 849,
		height: 1200,
	},
	{
		label: "Fight Club",
		imgUrl: "/img-filter/fight-club.jpg",
		backgroundColor: "bg-green-400",
		width: 736,
		height: 736,
	},
	{
		label: "Ocean",
		imgUrl: "/img-filter/ocean.jpg",
		backgroundColor: "bg-blue-400",
		width: 1042,
		height: 1461,
	},
	{
		label: "Paint 1",
		imgUrl: "/img-filter/paint-1.jpg",
		backgroundColor: "bg-blue-400",
		width: 1142,
		height: 1680,
	},
	{
		label: "Paint 2",
		imgUrl: "/img-filter/paint-2.jpg",
		backgroundColor: "bg-blue-400",
		width: 736,
		height: 1053,
	},
	{
		label: "Stormtrooper",
		imgUrl: "/img-filter/stormtrooper.jpg",
		backgroundColor: "bg-blue-400",
		width: 1080,
		height: 1319,
	},
	{
		label: "Superman",
		imgUrl: "/img-filter/superman.jpg",
		backgroundColor: "bg-blue-400",
		width: 1200,
		height: 1821,
	},
	{
		label: "The Bear",
		imgUrl: "/img-filter/the-bear.jpg",
		backgroundColor: "bg-blue-400",
		width: 888,
		height: 1751,
	},
	{
		label: "Toy Story",
		imgUrl: "/img-filter/toy-story-1.jpg",
		backgroundColor: "bg-blue-400",
		width: 640,
		height: 940,
	},
	{
		label: "You are the Apple",
		imgUrl: "/img-filter/you-are-the-apple-of-my-eye.jpg",
		backgroundColor: "bg-blue-400",
		width: 726,
		height: 552,
	},
];